### ISSUE TITLE
AutoPagerize; перенаправление 

### ISSUE THREAD

**Issue by yo8z6gv** [NC22/KellyCImageDownloader#3]
хз, вроде норм. жалко что не работает вместе с "AutoPagerize". можешь сделать чтобы был автоматическое перенаправление с ебаного "joyreactor", "#.reactor", "reactor" на "old.reactor"?

**Comment by NC22** [comment]
Перенаправления не трогаю т.к. расширение касается модифицирования только реферов и политик cors в рамках своего основного функционала лишь чтобы корректно запрашивать медиа данные. Текущие обходы блокировок джоя тоже ни как не коррелируют с ними, а вот под редиректы нужно будет менять фоновые скрипты чисто ради реакторских костылей. И мб уточнишь подробнее т.к. не совсем понятна суть проблемы. 

Касательно пагинации без проблем. В новой версии будет, уже правку докинул. Как прочекаю более глобальные правки, закину обнову в магазин.
